/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacio;

import capaDomini.Usuari.CtrlUser;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import static java.lang.Thread.sleep;

/**
 *
 * @author Oriolcapo
 */
public class GestioUsuari extends javax.swing.JPanel {

    private static String user;
    private static String oldPsw;
    private static String newPsw;
    private static String newPsw2;
    private static CtrlPresentacio CP;
    /**
     * Creates new form GestioUsuari
     */
    public GestioUsuari(String user, CtrlPresentacio CP) {
        this.user = user;
        this.CP = CP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserSettingsPanel = new javax.swing.JPanel();
        PasswordTitle = new javax.swing.JLabel();
        passwordFieldOld = new javax.swing.JTextField();
        NewPasswordTitle = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        ImgSettings = new javax.swing.JLabel();
        errorPasswordLabel = new javax.swing.JLabel();
        repeatErrorLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        repeatField = new javax.swing.JTextField();
        PswChangedLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 500));
        setLayout(new java.awt.CardLayout());

        UserSettingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User settings", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        UserSettingsPanel.setMaximumSize(new java.awt.Dimension(600, 500));
        UserSettingsPanel.setMinimumSize(new java.awt.Dimension(590, 490));

        PasswordTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PasswordTitle.setText("Change Password");

        passwordFieldOld.setText("Introduce your password...");
        passwordFieldOld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldOldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldOldFocusLost(evt);
            }
        });
        passwordFieldOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldOldActionPerformed(evt);
            }
        });

        NewPasswordTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NewPasswordTitle.setText("New Password");

        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/SaveButtonn.png"))); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/ExitButton.png"))); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        ImgSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/UserSettings.png"))); // NOI18N

        errorPasswordLabel.setForeground(new java.awt.Color(255, 0, 0));

        repeatErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        passwordField.setText("Introduce your new password...");
        passwordField.setMaximumSize(new java.awt.Dimension(566, 30));
        passwordField.setMinimumSize(new java.awt.Dimension(566, 30));
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        repeatField.setText("Repeat your new password...");
        repeatField.setMaximumSize(new java.awt.Dimension(566, 30));
        repeatField.setMinimumSize(new java.awt.Dimension(566, 30));
        repeatField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                repeatFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                repeatFieldFocusLost(evt);
            }
        });
        repeatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatFieldActionPerformed(evt);
            }
        });

        PswChangedLabel.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout UserSettingsPanelLayout = new javax.swing.GroupLayout(UserSettingsPanel);
        UserSettingsPanel.setLayout(UserSettingsPanelLayout);
        UserSettingsPanelLayout.setHorizontalGroup(
            UserSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserSettingsPanelLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(ImgSettings)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(UserSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserSettingsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SaveButton)
                        .addGap(27, 27, 27)
                        .addComponent(ExitButton)
                        .addGap(32, 32, 32))
                    .addGroup(UserSettingsPanelLayout.createSequentialGroup()
                        .addGroup(UserSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UserSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(repeatField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UserSettingsPanelLayout.createSequentialGroup()
                                    .addComponent(NewPasswordTitle)
                                    .addGap(18, 18, 18)
                                    .addComponent(repeatErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(passwordFieldOld)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UserSettingsPanelLayout.createSequentialGroup()
                                    .addComponent(PasswordTitle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(errorPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(PswChangedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UserSettingsPanelLayout.setVerticalGroup(
            UserSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserSettingsPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(UserSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordTitle)
                    .addComponent(errorPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(passwordFieldOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewPasswordTitle)
                    .addComponent(repeatErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(repeatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PswChangedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(UserSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(ExitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(ImgSettings)
                .addGap(67, 67, 67))
        );

        add(UserSettingsPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldOldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldOldActionPerformed

    private void passwordFieldOldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldOldFocusGained
        passwordFieldOld.setText("");
    }//GEN-LAST:event_passwordFieldOldFocusGained

    private void passwordFieldOldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldOldFocusLost
        if (passwordFieldOld.getText().isEmpty()) passwordFieldOld.setText("Introduce your password...");
    }//GEN-LAST:event_passwordFieldOldFocusLost

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        String incPsw = "<html>Incorrect Password</html>";
        String pswDontMatch = "<html>New passwords don't match</html>";
        String pswEmpty = "<html>Insert new passwords</html>";
        String pswChanged = "<html>You have changed your password correctly</html>";
        String pswSize = "<html>Password must have at least 5 characters</html>";       
        
        String ePL = errorPasswordLabel.getText();
        String rEL = repeatErrorLabel.getText ();
        oldPsw = passwordFieldOld.getText();
        newPsw = passwordField.getText ();
        newPsw2 = repeatField.getText ();        
        
        if (!CP.comprovarUsuari(user, oldPsw)) {
            errorPasswordLabel.setText(incPsw);
        }
        
        if (!newPsw.equals(newPsw2)) {
            repeatErrorLabel.setText(pswDontMatch);
        }
        else if (newPsw.equals(newPsw2) && newPsw.length() < 5) {
            repeatErrorLabel.setText(pswSize);
        }
        
        if (CP.comprovarUsuari(user, oldPsw) && ePL.equals(incPsw)) {
            errorPasswordLabel.setText("");
        }
        if (newPsw.equals(newPsw2) && (rEL.equals(pswDontMatch)||rEL.equals(pswEmpty)||newPsw.length() >= 5)) {
            repeatErrorLabel.setText("");
        }

        if (CP.comprovarUsuari(user, oldPsw) && newPsw.equals(newPsw2)  && newPsw.length() >= 5) {
            CP.changePassword(user,newPsw);
            CtrlUser.modificaUsuari(user,user,newPsw);
            PswChangedLabel.setText(pswChanged);
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        // TODO add your handling code here:
        passwordField.setText("");
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        // TODO add your handling code here:
        if (passwordField.getText().isEmpty()) passwordField.setText("Introduce your new password...");
    }//GEN-LAST:event_passwordFieldFocusLost

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void repeatFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repeatFieldFocusGained
        // TODO add your handling code here:
        repeatField.setText("");
    }//GEN-LAST:event_repeatFieldFocusGained

    private void repeatFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repeatFieldFocusLost
        // TODO add your handling code here:
        if (repeatField.getText().isEmpty()) repeatField.setText("Repeat your new password...");
    }//GEN-LAST:event_repeatFieldFocusLost

    private void repeatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repeatFieldActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        removeAll();
        repaint();
        revalidate();
        //afegint JPanel
        add(new WelcomeToKenken());
        repaint();
        revalidate();
    }//GEN-LAST:event_ExitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel ImgSettings;
    private javax.swing.JLabel NewPasswordTitle;
    private javax.swing.JLabel PasswordTitle;
    private javax.swing.JLabel PswChangedLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JPanel UserSettingsPanel;
    private javax.swing.JLabel errorPasswordLabel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField passwordFieldOld;
    private javax.swing.JLabel repeatErrorLabel;
    private javax.swing.JTextField repeatField;
    // End of variables declaration//GEN-END:variables
}
