/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacio;

/**
 *
 * @author edu
 */
public class PantallaInici extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaInici() {
        initComponents();
        String text = "<html><u>Not registered?</u></html>";
        Registration_Link.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogIn = new javax.swing.JPanel();
        Username_Label = new javax.swing.JLabel();
        Username_Field = new javax.swing.JTextField();
        Password_Label = new javax.swing.JLabel();
        Password_Field = new javax.swing.JPasswordField();
        LogIn_Button = new javax.swing.JButton();
        Registration_Link = new javax.swing.JLabel();
        KenKen = new javax.swing.JPanel();
        KenKenImage = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Preferences = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KenKen");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        LogIn.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));
        LogIn.setNextFocusableComponent(Username_Field);
        LogIn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                LogInPropertyChange(evt);
            }
        });

        Username_Label.setText("Username");
        Username_Label.setAlignmentX(1.0F);

        Username_Field.setAlignmentX(1.0F);
        Username_Field.setNextFocusableComponent(Password_Field);
        Username_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_FieldActionPerformed(evt);
            }
        });

        Password_Label.setText("Password");
        Password_Label.setAlignmentX(1.0F);

        Password_Field.setAlignmentX(1.0F);

        LogIn_Button.setText("Log In");
        LogIn_Button.setToolTipText("Log In");
        LogIn_Button.setAlignmentX(1.0F);
        LogIn_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_ButtonActionPerformed(evt);
            }
        });

        Registration_Link.setForeground(new java.awt.Color(0, 6, 255));
        Registration_Link.setText("Not registered?");
        Registration_Link.setAlignmentX(1.0F);
        Registration_Link.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registration_Link.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Registration_LinkFocusGained(evt);
            }
        });
        Registration_Link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Registration_LinkMouseClicked(evt);
            }
        });
        Registration_Link.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Registration_LinkPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout LogInLayout = new javax.swing.GroupLayout(LogIn);
        LogIn.setLayout(LogInLayout);
        LogInLayout.setHorizontalGroup(
            LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username_Field)
                    .addComponent(Password_Field)
                    .addGroup(LogInLayout.createSequentialGroup()
                        .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username_Label)
                            .addComponent(Password_Label))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(LogInLayout.createSequentialGroup()
                        .addComponent(Registration_Link)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(LogIn_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        LogInLayout.setVerticalGroup(
            LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Username_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Registration_Link)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(LogIn_Button)
                .addContainerGap())
        );

        KenKen.setBorder(null);
        KenKen.setPreferredSize(new java.awt.Dimension(200, 200));

        KenKenImage.setIcon(new javax.swing.ImageIcon("/home/edu/Documentos/FIB/5qt_15-16/PROP/KenKen/img/kenken.jpg")); // NOI18N

        javax.swing.GroupLayout KenKenLayout = new javax.swing.GroupLayout(KenKen);
        KenKen.setLayout(KenKenLayout);
        KenKenLayout.setHorizontalGroup(
            KenKenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(KenKenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(KenKenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(KenKenImage)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        KenKenLayout.setVerticalGroup(
            KenKenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
            .addGroup(KenKenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(KenKenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(KenKenImage)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Menu.setName(""); // NOI18N

        File.setText("File");

        Preferences.setText("Preferences");
        Preferences.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PreferencesMouseClicked(evt);
            }
        });
        File.add(Preferences);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        Menu.add(File);

        Help.setText("Help");

        About.setIcon(new javax.swing.ImageIcon("/home/edu/Documentos/FIB/5qt_15-16/PROP/KenKen/img/Help.png")); // NOI18N
        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        Help.add(About);

        Menu.add(Help);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(KenKen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KenKen, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    private void LogIn_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogIn_ButtonActionPerformed

    private void Username_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_FieldActionPerformed

    private void PreferencesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreferencesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PreferencesMouseClicked

    private void Registration_LinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Registration_LinkMouseClicked
        SignIn login = new SignIn();
        login.setVisible(true);
    }//GEN-LAST:event_Registration_LinkMouseClicked

    private void Registration_LinkPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Registration_LinkPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_Registration_LinkPropertyChange

    private void Registration_LinkFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Registration_LinkFocusGained

    }//GEN-LAST:event_Registration_LinkFocusGained

    private void LogInPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_LogInPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JPanel KenKen;
    private javax.swing.JLabel KenKenImage;
    private javax.swing.JPanel LogIn;
    private javax.swing.JButton LogIn_Button;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JMenuItem Preferences;
    private javax.swing.JLabel Registration_Link;
    private javax.swing.JTextField Username_Field;
    private javax.swing.JLabel Username_Label;
    // End of variables declaration//GEN-END:variables
}
