/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacio;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author Oriolcapo
 */
public class Pantalla_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_Principal
     */
    public Pantalla_Principal() {
        initComponents();
        
        Toolkit tool = Toolkit.getDefaultToolkit();
        Dimension dim = new Dimension(tool.getScreenSize());
        int height = (int) dim.getHeight();
        int width = (int) dim.getWidth();
        setLocation(width/2 - getWidth()/2, height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_GU = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton_GestorUsuari = new javax.swing.JButton();
        jButton_CrearKenken = new javax.swing.JButton();
        jButton_JugarKenKen = new javax.swing.JButton();
        jButton_ConsultarRanking = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel_GU.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel_GULayout = new javax.swing.GroupLayout(jPanel_GU);
        jPanel_GU.setLayout(jPanel_GULayout);
        jPanel_GULayout.setHorizontalGroup(
            jPanel_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel_GULayout.setVerticalGroup(
            jPanel_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel_GU, "card2");

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jButton_GestorUsuari.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_GestorUsuari.setText("User Manager");
        jButton_GestorUsuari.setToolTipText("");
        jButton_GestorUsuari.setMaximumSize(new java.awt.Dimension(164, 110));
        jButton_GestorUsuari.setMinimumSize(new java.awt.Dimension(164, 110));
        jButton_GestorUsuari.setPreferredSize(new java.awt.Dimension(164, 110));
        jButton_GestorUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestorUsuariActionPerformed(evt);
            }
        });

        jButton_CrearKenken.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_CrearKenken.setText("Create KenKen");
        jButton_CrearKenken.setMaximumSize(new java.awt.Dimension(164, 110));
        jButton_CrearKenken.setMinimumSize(new java.awt.Dimension(164, 110));
        jButton_CrearKenken.setPreferredSize(new java.awt.Dimension(164, 110));
        jButton_CrearKenken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearKenkenActionPerformed(evt);
            }
        });

        jButton_JugarKenKen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_JugarKenKen.setText("Play KenKen");
        jButton_JugarKenKen.setMaximumSize(new java.awt.Dimension(164, 110));
        jButton_JugarKenKen.setMinimumSize(new java.awt.Dimension(164, 110));
        jButton_JugarKenKen.setPreferredSize(new java.awt.Dimension(164, 110));
        jButton_JugarKenKen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_JugarKenKenActionPerformed(evt);
            }
        });

        jButton_ConsultarRanking.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_ConsultarRanking.setText("Ranking");
        jButton_ConsultarRanking.setMaximumSize(new java.awt.Dimension(164, 110));
        jButton_ConsultarRanking.setMinimumSize(new java.awt.Dimension(164, 110));
        jButton_ConsultarRanking.setPreferredSize(new java.awt.Dimension(164, 110));
        jButton_ConsultarRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultarRankingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_ConsultarRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_JugarKenKen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_CrearKenken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_GestorUsuari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton_GestorUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_CrearKenken, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton_JugarKenKen, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_ConsultarRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GestorUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestorUsuariActionPerformed
        // TODO add your handling code here:
        //esborrant JPanel
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        //afegint JPanel
        jPanel2.add(new GestioUsuari());
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton_GestorUsuariActionPerformed

    private void jButton_CrearKenkenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearKenkenActionPerformed
        // TODO add your handling code here:
        //esborrant JPanel
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        //afegint JPanel
        jPanel2.add(new Crear_Kenken());
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton_CrearKenkenActionPerformed

    private void jButton_JugarKenKenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_JugarKenKenActionPerformed
        // TODO add your handling code here:
        //esborrant JPanel
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        //afegint JPanel
        jPanel2.add(new JugarKenken());
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton_JugarKenKenActionPerformed

    private void jButton_ConsultarRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultarRankingActionPerformed
        // TODO add your handling code here:
        //esborrant JPanel
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        //afegint JPanel
        jPanel2.add(new Ranking());
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton_ConsultarRankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ConsultarRanking;
    private javax.swing.JButton jButton_CrearKenken;
    private javax.swing.JButton jButton_GestorUsuari;
    private javax.swing.JButton jButton_JugarKenKen;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_GU;
    // End of variables declaration//GEN-END:variables
}
