/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacio;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Oriolcapo
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private static String user;
    private javax.swing.JFrame parent;
    private CtrlPresentacio CP;
    /**
     * Creates new form Pantalla_Principal
     */
    public PantallaPrincipal(String user, CtrlPresentacio CP, javax.swing.JFrame pare) {
        initComponents();
        parent = pare;
        this.user = user;
        this.CP = CP;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        
        Toolkit tool = Toolkit.getDefaultToolkit();
        Dimension dim = new Dimension(tool.getScreenSize());
        int height = (int) dim.getHeight();
        int width = (int) dim.getWidth();
        setLocation(width/2 - getWidth()/2, height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        welcomeToKenken1 = new capaPresentacio.WelcomeToKenken();
        jButton_GestorUsuari = new javax.swing.JButton();
        jButton_CrearKenken = new javax.swing.JButton();
        jButton_JugarKenKen = new javax.swing.JButton();
        jButton_ConsultarRanking = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        exitItemMenu = new javax.swing.JMenuItem();
        options = new javax.swing.JMenu();
        userMngrItem = new javax.swing.JMenuItem();
        submenuCreateKenKen = new javax.swing.JMenu();
        manItem = new javax.swing.JMenuItem();
        parItem = new javax.swing.JMenuItem();
        submenuPlayKenKen = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        submenuRanking = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("KenKen");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel2.setMaximumSize(new java.awt.Dimension(598, 496));
        jPanel2.setMinimumSize(new java.awt.Dimension(598, 496));
        jPanel2.setPreferredSize(new java.awt.Dimension(598, 496));
        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel2.add(welcomeToKenken1, "card2");

        getContentPane().add(jPanel2);
        jPanel2.setBounds(190, 34, 600, 496);

        jButton_GestorUsuari.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_GestorUsuari.setText("User Manager");
        jButton_GestorUsuari.setToolTipText("");
        jButton_GestorUsuari.setMaximumSize(new java.awt.Dimension(164, 110));
        jButton_GestorUsuari.setMinimumSize(new java.awt.Dimension(164, 110));
        jButton_GestorUsuari.setPreferredSize(new java.awt.Dimension(164, 110));
        jButton_GestorUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestorUsuariActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestorUsuari);
        jButton_GestorUsuari.setBounds(14, 34, 166, 110);

        jButton_CrearKenken.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_CrearKenken.setText("Create KenKen");
        jButton_CrearKenken.setMaximumSize(new java.awt.Dimension(164, 110));
        jButton_CrearKenken.setMinimumSize(new java.awt.Dimension(164, 110));
        jButton_CrearKenken.setPreferredSize(new java.awt.Dimension(164, 110));
        jButton_CrearKenken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearKenkenActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CrearKenken);
        jButton_CrearKenken.setBounds(14, 162, 166, 108);

        jButton_JugarKenKen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_JugarKenKen.setText("Play KenKen");
        jButton_JugarKenKen.setMaximumSize(new java.awt.Dimension(164, 110));
        jButton_JugarKenKen.setMinimumSize(new java.awt.Dimension(164, 110));
        jButton_JugarKenKen.setPreferredSize(new java.awt.Dimension(164, 110));
        jButton_JugarKenKen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_JugarKenKenActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_JugarKenKen);
        jButton_JugarKenKen.setBounds(14, 294, 166, 109);

        jButton_ConsultarRanking.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_ConsultarRanking.setText("Ranking");
        jButton_ConsultarRanking.setMaximumSize(new java.awt.Dimension(164, 110));
        jButton_ConsultarRanking.setMinimumSize(new java.awt.Dimension(164, 110));
        jButton_ConsultarRanking.setPreferredSize(new java.awt.Dimension(164, 110));
        jButton_ConsultarRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultarRankingActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ConsultarRanking);
        jButton_ConsultarRanking.setBounds(14, 421, 166, 109);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/background.jpeg"))); // NOI18N
        backgroundLabel.setPreferredSize(new java.awt.Dimension(800, 580));
        backgroundLabel.setRequestFocusEnabled(false);
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 800, 575);

        file.setText("File");

        exitItemMenu.setText("Exit");
        exitItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemMenuActionPerformed(evt);
            }
        });
        file.add(exitItemMenu);

        Menu.add(file);

        options.setText("Options");

        userMngrItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/UserManagerIcon.png"))); // NOI18N
        userMngrItem.setText("User Manager");
        userMngrItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userMngrItem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        userMngrItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMngrItemActionPerformed(evt);
            }
        });
        options.add(userMngrItem);

        submenuCreateKenKen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/CreateIcon.png"))); // NOI18N
        submenuCreateKenKen.setText("Create KenKen");
        submenuCreateKenKen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        submenuCreateKenKen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        manItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/ManuallyIcon.png"))); // NOI18N
        manItem.setText("Manually");
        manItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manItemActionPerformed(evt);
            }
        });
        submenuCreateKenKen.add(manItem);

        parItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/ParametersIcon.png"))); // NOI18N
        parItem.setText("By Parameters");
        submenuCreateKenKen.add(parItem);

        options.add(submenuCreateKenKen);

        submenuPlayKenKen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/playIcon.png"))); // NOI18N
        submenuPlayKenKen.setText("Play KenKen");
        submenuPlayKenKen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        submenuPlayKenKen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/ResumeIcon.png"))); // NOI18N
        jMenuItem1.setText("Resume saved game...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        submenuPlayKenKen.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/DBIcon.png"))); // NOI18N
        jMenuItem2.setText("Select a KenKen");
        submenuPlayKenKen.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/RandomIcon.png"))); // NOI18N
        jMenuItem3.setText("Random KenKen");
        submenuPlayKenKen.add(jMenuItem3);

        options.add(submenuPlayKenKen);

        submenuRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaPresentacio/img/RankingIcon.png"))); // NOI18N
        submenuRanking.setText("Ranking");
        submenuRanking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        submenuRanking.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        options.add(submenuRanking);

        Menu.add(options);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GestorUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestorUsuariActionPerformed
        // TODO add your handling code here:
        //esborrant JPanel
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        //afegint JPanel
        jPanel2.add(new GestioUsuari(user,CP));
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton_GestorUsuariActionPerformed

    private void jButton_CrearKenkenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearKenkenActionPerformed
        // TODO add your handling code here:
        //esborrant JPanel
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        //afegint JPanel
        jPanel2.add(new CrearKenken(user,this));
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton_CrearKenkenActionPerformed

    private void jButton_JugarKenKenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_JugarKenKenActionPerformed
        // TODO add your handling code here:
        //esborrant JPanel
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        //afegint JPanel
        jPanel2.add(new JugarKenken(user,this));
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton_JugarKenKenActionPerformed

    private void jButton_ConsultarRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultarRankingActionPerformed
        // TODO add your handling code here:
        //esborrant JPanel
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        //afegint JPanel
        jPanel2.add(new Ranking(CP));
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton_ConsultarRankingActionPerformed

    private void exitItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemMenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitItemMenuActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Object[] opciones = {"Accept", "Cancel"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,
                "Do you want to logout?",
                "Confirmation Message",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,
                null,opciones,"Acept");
        if (eleccion == JOptionPane.YES_OPTION) {
            PantallaInici P = new PantallaInici(CP);
            dispose();
        }
        else {
            PantallaPrincipal P = new PantallaPrincipal(user,CP,parent);
        }
    }//GEN-LAST:event_formWindowClosing

    private void manItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void userMngrItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMngrItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userMngrItemActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JMenuItem exitItemMenu;
    private javax.swing.JMenu file;
    private javax.swing.JButton jButton_ConsultarRanking;
    private javax.swing.JButton jButton_CrearKenken;
    private javax.swing.JButton jButton_GestorUsuari;
    private javax.swing.JButton jButton_JugarKenKen;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem manItem;
    private javax.swing.JMenu options;
    private javax.swing.JMenuItem parItem;
    private javax.swing.JMenu submenuCreateKenKen;
    private javax.swing.JMenu submenuPlayKenKen;
    private javax.swing.JMenu submenuRanking;
    private javax.swing.JMenuItem userMngrItem;
    private capaPresentacio.WelcomeToKenken welcomeToKenken1;
    // End of variables declaration//GEN-END:variables
}
