/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacio;

import com.sun.glass.events.KeyEvent;
import java.text.DecimalFormat;

/**
 *
 * @author Jan
 */
public class PersonalR extends javax.swing.JPanel {
    
    private CtrlPresentacio CP;
    
    /**
     * Creates new form PersonalR
     */
    public PersonalR(CtrlPresentacio CP) {
        initComponents();
        this.CP = CP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_label = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        jResoltsLabel = new javax.swing.JLabel();
        avgpistesLabel = new javax.swing.JLabel();
        timesLabel = new javax.swing.JLabel();
        threeLabel = new javax.swing.JLabel();
        fourLabel = new javax.swing.JLabel();
        fiveLabel = new javax.swing.JLabel();
        sixLabel = new javax.swing.JLabel();
        sevenLabel = new javax.swing.JLabel();
        eightLabel = new javax.swing.JLabel();
        nineLabel = new javax.swing.JLabel();
        jResolts = new javax.swing.JLabel();
        avgpistes = new javax.swing.JLabel();
        threetime = new javax.swing.JLabel();
        fourtime = new javax.swing.JLabel();
        fivetime = new javax.swing.JLabel();
        sixtime = new javax.swing.JLabel();
        seventime = new javax.swing.JLabel();
        eighttime = new javax.swing.JLabel();
        ninetime = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Ranking", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        user_label.setText("Username");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameFieldKeyPressed(evt);
            }
        });

        findButton.setText("Find");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        jResoltsLabel.setText("Jocs resolts:");

        avgpistesLabel.setText("Mitjana de pistes: ");

        timesLabel.setText("Millors temps:");

        threeLabel.setText("3x3:");

        fourLabel.setText("4x4:");

        fiveLabel.setText("5x5:");

        sixLabel.setText("6x6:");

        sevenLabel.setText("7x7:");

        eightLabel.setText("8x8:");

        nineLabel.setText("9x9:");

        jResolts.setText("-");

        avgpistes.setText("-");

        threetime.setText("-");

        fourtime.setText("-");

        fivetime.setText("-");

        sixtime.setText("-");

        seventime.setText("-");

        eighttime.setText("-");

        ninetime.setText("-");

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(user_label, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(threeLabel)
                                .addComponent(timesLabel)
                                .addComponent(fourLabel)
                                .addComponent(fiveLabel)
                                .addComponent(sixLabel)
                                .addComponent(sevenLabel)
                                .addComponent(eightLabel)
                                .addComponent(nineLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(threetime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fourtime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fivetime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sixtime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seventime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eighttime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ninetime, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(avgpistesLabel)
                            .addGap(18, 18, 18)
                            .addComponent(avgpistes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)
                            .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jResoltsLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jResolts, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(84, 84, 84))))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jResoltsLabel)
                    .addComponent(jResolts))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgpistesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avgpistes))
                .addGap(18, 18, 18)
                .addComponent(timesLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threeLabel)
                    .addComponent(threetime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourLabel)
                    .addComponent(fourtime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fivetime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixtime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seventime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eighttime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ninetime))
                .addGap(18, 18, 18)
                .addComponent(errorLabel)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        // TODO add your handling code here:
        String user = usernameField.getText();
        if (CP.existeixUsuari(user)) {
            if (CP.obtenirResoltsRP(user) == 0) {
                buidaAll();
                jResolts.setText("0");
                errorLabel.setText("<html>No games played by this user</html>");
            }
            else {
                obtenirAll(user);
                errorLabel.setText("");
            }
        }
        else {
            buidaAll();
            errorLabel.setText("<html>Username incorrect</html>");
        }        
    }//GEN-LAST:event_findButtonActionPerformed

    private void usernameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String user = usernameField.getText();
            if (CP.existeixUsuari(user)) {
                if (CP.obtenirResoltsRP(user) == 0) {
                    buidaAll();
                    jResolts.setText("0");
                    errorLabel.setText("<html>No games played by this user</html>");
                }
                else {
                    obtenirAll(user);
                    errorLabel.setText("");
                }
            }
            else {
                buidaAll();
                errorLabel.setText("<html>Username incorrect</html>");
            }
        }
    }//GEN-LAST:event_usernameFieldKeyPressed

    private void obtenirAll (String user) {
        DecimalFormat decimals = new DecimalFormat("0.0000");
        jResolts.setText(Integer.toString(CP.obtenirResoltsRP(user)));
        avgpistes.setText(decimals.format(CP.obtenirPistesRP(user)));
        threetime.setText(decimals.format(CP.obtenirTempsRP(user, "3x3")));
        fourtime.setText(decimals.format(CP.obtenirTempsRP(user, "4x4")));
        fivetime.setText(decimals.format(CP.obtenirTempsRP(user, "5x5")));
        sixtime.setText(decimals.format(CP.obtenirTempsRP(user, "6x6")));
        seventime.setText(decimals.format(CP.obtenirTempsRP(user, "7x7")));
        eighttime.setText(decimals.format(CP.obtenirTempsRP(user, "8x8")));
        ninetime.setText(decimals.format(CP.obtenirTempsRP(user, "9x9")));
    }
    
    private void buidaAll() {
        jResolts.setText("-");
        avgpistes.setText("-");
        threetime.setText("-");
        fourtime.setText("-");
        fivetime.setText("-");
        sixtime.setText("-");
        seventime.setText("-");
        eighttime.setText("-");
        ninetime.setText("-");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgpistes;
    private javax.swing.JLabel avgpistesLabel;
    private javax.swing.JLabel eightLabel;
    private javax.swing.JLabel eighttime;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton findButton;
    private javax.swing.JLabel fiveLabel;
    private javax.swing.JLabel fivetime;
    private javax.swing.JLabel fourLabel;
    private javax.swing.JLabel fourtime;
    private javax.swing.JLabel jResolts;
    private javax.swing.JLabel jResoltsLabel;
    private javax.swing.JLabel nineLabel;
    private javax.swing.JLabel ninetime;
    private javax.swing.JLabel sevenLabel;
    private javax.swing.JLabel seventime;
    private javax.swing.JLabel sixLabel;
    private javax.swing.JLabel sixtime;
    private javax.swing.JLabel threeLabel;
    private javax.swing.JLabel threetime;
    private javax.swing.JLabel timesLabel;
    private javax.swing.JLabel user_label;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
