/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacio;

/**
 *
 * @author Oriolcapo
 */
public class WelcomeToKenken extends javax.swing.JPanel {

    /**
     * Creates new form WelcomeToKenken
     */
    public WelcomeToKenken() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_GU = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel_GU.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_GU.setMaximumSize(new java.awt.Dimension(598, 496));
        jPanel_GU.setMinimumSize(new java.awt.Dimension(598, 496));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("WELCOME TO KENKEN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("CHOOSE AN OPTION");

        javax.swing.GroupLayout jPanel_GULayout = new javax.swing.GroupLayout(jPanel_GU);
        jPanel_GU.setLayout(jPanel_GULayout);
        jPanel_GULayout.setHorizontalGroup(
            jPanel_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_GULayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel_GULayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel_GULayout.setVerticalGroup(
            jPanel_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_GULayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        add(jPanel_GU, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_GU;
    // End of variables declaration//GEN-END:variables
}
